CREATE TABLE services
(
    service_id          int4 generated by default as identity primary key,
    service_name        varchar(255)   not null,
    service_price       decimal(10, 2) not null,
    service_description varchar(255),
    image_url           varchar(255)
);

CREATE TABLE teams
(
    team_id   int4 generated by default as identity primary key,
    team_name varchar(255) not null
);

CREATE TABLE users
(
    user_id    int4 generated by default as identity primary key,
    password   varchar(255) not null,
    role       varchar(255) not null,
    email      varchar(255) not null unique,
    first_name varchar(255) not null,
    last_name  varchar(255) not null,
    team_id    int4 references teams (team_id)
);

CREATE TABLE orders
(
    order_id       int4 generated by default as identity primary key,
    order_made     timestamp      not null,
    order_date     timestamp      not null,
    order_price    decimal(10, 2) not null,
    user_id        int4 references users (user_id),
    team_id        int4 references teams (team_id),
    payment_method varchar(255)
);

CREATE TABLE equipment
(
    equipment_id          int4 generated by default as identity primary key,
    equipment_name        varchar(255)   not null,
    equipment_price       decimal(10, 2) not null,
    image_url             varchar(255),
    equipment_description varchar(255)
);

CREATE TABLE feedback
(
    feedback_id int4 generated by default as identity primary key,
    description varchar(255) not null,
    user_id     int4 references users (user_id)
);

CREATE TABLE order_equipment
(
    id           int4 generated by default as identity primary key,
    order_id     int4 references orders (order_id),
    equipment_id int4 references equipment (equipment_id)
);


CREATE TABLE order_service
(
    id         int4 generated by default as identity primary key,
    order_id   int4 references orders (order_id),
    service_id int4 references services (service_id)

);
